language: python
python:
  - 3.7

install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda info -a
  - conda env create -f environment.yml
  - source activate momepy_guide
  - conda list
  - python -m ipykernel install --user --name mmp_guide --display-name "Python (momepy_guide)"

script:
  - mkdir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=2000 content/graph/centrality.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/getting_started.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/elements/*.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/simple/*.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/combined/*.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/weights/*.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/graph/convert.ipynb --output-dir content/output
  - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1000 content/graph/network.ipynb --output-dir content/output
  - rm -rf content/output
