language: python
python:
  - 3.7

install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda info -a
  - conda env create -f environment.yml
  - source activate momepy_guide
  - conda list
  - python -m ipykernel install --user --name mmp_guide --display-name "Python (momepy_guide)"

script:
  - jupyter-book run content/getting_started.ipynb
  - jupyter-book run content/elements
  - jupyter-book run content/simple
  - jupyter-book run content/combined
  - jupyter-book run content/weights
  - jupyter-book run content/graph
