name: binder
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - libpysal
  - networkx
  - tqdm
  - mapclassify
  - momepy
  - matplotlib
  - rtree
  - osmnx
  - pip:
    - inequality
